version: '3.4'

services:

  sql.data:
    image: microsoft/mssql-server-linux

  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  captrans:
    image: ${DOCKER_REGISTRY-}captrans
    build:
      context: .
      dockerfile: src/CapTrans/Dockerfile
